#!/usr/bin/env bash
set -u # make sure all varaible is set

ARGUMENT_LIST=(
  "dst:"  # `:` means requirements
  "src:"
  "bk_dir:"
  "ex_dir:"
)

# Default empty values of arguments
execution=true
dst=""
src=""
backup_dir=""
exclude_dir=""

# read arguments
opts=$(getopt \
  --longoptions "$(printf "%s," "${ARGUMENT_LIST[@]}")" \
  --name "$(basename "$0")" \
  --options "h" \
  -- "$@"
)

# if sending invalid option, stop script
if [ $? -ne 0 ]; then
  echo "========================== Error:Invalid option provided to rclone_local_sync.sh at $(/usr/bin/date) ================================" >> /home/ywt01/Documents/tmp/rclone_local_sync_err.log
  exit 1
fi

eval set -- "$opts" # Note: In order to handle the argument containing space, the quotes around '$opts': they are essential!

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dst)
      dst="$2" # Note: In order to handle the argument containing space, the quotes around '$2': they are essential!
      shift 2 # The 'shift' eats a commandline argument, i.e. converts $1=a, $2=b, $3=c, $4=d into $1=b, $2=c, $3=d. shift 2 moves it all the way to $1=c, $2=d. It's done since that particular branch uses an argument, so it has to remove two things from the list (the -r and the argument following it) not just one.
      ;;

    --src)
      src="$2"
      shift 2
      ;;

    --bk_dir)
      backup_dir="$2"
      shift 2
      ;;

    --ex_dir)
      exclude_dir="$2"
      shift 2
      ;;

    -h)
      echo "===============execution example:===============
rclone_local_sync.sh --src <folder_name> --dst <folder_name> --bk_dir <folder_name>

===============options explanation:===============
--dst : destination directory
--src : soruce dircectory
--bk_dir : backup directory
--ex_dir : excluded sync directory
"
      execution=false
      shift 2
      ;;

    *)
      if [ "$1" != "--" ]; then
           echo "don't has $1 option"
      fi
      break
      ;;
  esac
done


if $execution ; then
    /usr/bin/rclone sync "$src" "$dst" -P --delete-after --backup-dir "$backup_dir" --exclude "$exclude_dir/**" 2>>/home/ywt01/Documents/tmp/rclone_local_sync_err.log
fi
