# Define the services (containers) that will be part of this application
services:
  # Service for JupyterLab
  jupyterlab:
    # Specify the Docker image to use for this service
    image: abc50111/jupyterlab:latest
    # Assign a specific name to the container
    container_name: py_dev_env
    # Map ports from the host to the container.
    # The left side is the host port, and the right side is the container port.
    # JupyterLab typically runs on port 8888 inside the container.
    ports:
      - "25002:8888" # Updated port mapping as per your command
    # Restart the container if it stops for any reason, unless explicitly stopped
    restart: unless-stopped
    # Mount volumes for persistent storage and configuration
    volumes:
      # Mount the host's localtime for correct timezone inside the container
      - /etc/localtime:/etc/localtime:ro
      # Mount your local codes directory into the container's workspace
      - /home/ywt01_dmlab/Documents:/workspace
    # Configure runtime and GPU access for the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Specify the Docker runtime to use (e.g., nvidia for GPU support)
    runtime: nvidia
